"""recreate?

Revision ID: 457d804f3f9d
Revises: 909131da3919
Create Date: 2025-05-14 00:25:42.652871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457d804f3f9d'
down_revision: Union[str, None] = '909131da3919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('darbovietes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', sa.String(length=50), nullable=False),
    sa.Column('miestas', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', sa.String(length=50), nullable=False),
    sa.Column('aktyvus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pareigos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', sa.String(length=50), nullable=False),
    sa.Column('aprasymas', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('darbuotojai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vardas', sa.String(length=50), nullable=True),
    sa.Column('pavarde', sa.String(length=50), nullable=True),
    sa.Column('asmens_kodas', sa.Integer(), nullable=True),
    sa.Column('gimimo_data', sa.Date(), nullable=True),
    sa.Column('atlyginimas', sa.Integer(), nullable=True),
    sa.Column('darboviete_id', sa.Integer(), nullable=False),
    sa.Column('departamentas_id', sa.Integer(), nullable=True),
    sa.Column('nuo_kada_dirba', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['darboviete_id'], ['darbovietes.id'], ),
    sa.ForeignKeyConstraint(['departamentas_id'], ['departamentai.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asmens_kodas')
    )
    op.create_table('darbuotojo_pareigos',
    sa.Column('darbuotojas_id', sa.Integer(), nullable=False),
    sa.Column('pareigos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['darbuotojas_id'], ['darbuotojai.id'], ),
    sa.ForeignKeyConstraint(['pareigos_id'], ['pareigos.id'], ),
    sa.PrimaryKeyConstraint('darbuotojas_id', 'pareigos_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darbuotojo_pareigos')
    op.drop_table('darbuotojai')
    op.drop_table('pareigos')
    op.drop_table('departamentai')
    op.drop_table('darbovietes')
    # ### end Alembic commands ###
