"""asmens kodas update to string, Darbuotojas table;

Revision ID: ab79d2debc6e
Revises: 457d804f3f9d
Create Date: 2025-05-14 00:48:38.231645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab79d2debc6e'
down_revision: Union[str, None] = '457d804f3f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('darbuotojai', 'asmens_kodas',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('darbuotojai', 'asmens_kodas',
               existing_type=sa.String(length=13),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
